import Equivariant.Spectra.Definition
import Equivariant.IndexingSystem
import Mathlib.Algebra.Group.Subgroup.Defs
import Mathlib.Data.Int.Basic

namespace Equivariant

universe u

variable {G : Type u} [Group G]

/-- Abstract `O`-slice cell data in the orthogonal-spectrum layer. -/
structure MainSliceCellData (G : Type u) [Group G] where
  fromSubgroup : Subgroup G
  toSubgroup : Subgroup G
  degree : ℤ
  realization : OrthogonalSpectrum G := ZeroSpectrum G

/--
Parameterized realization of slice cells inside the chosen orthogonal-spectrum model.
-/
structure SliceCellModel (G : Type u) [Group G] where
  cellObj : MainSliceCellData G → OrthogonalSpectrum G

/--
`O`-admissible level-`n` slice cell:
admissible transfer plus degree lower bound and nonnegativity.
-/
def IsMainSliceCell (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) (c : MainSliceCellData G) : Prop :=
  O.transfer c.fromSubgroup c.toSubgroup ∧ d O c.fromSubgroup n ≤ c.degree ∧ 0 ≤ c.degree

/-- Set of admissible level-`n` slice cells. -/
def MainSliceCells (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) : Set (MainSliceCellData G) :=
  {c | IsMainSliceCell O d n c}

/-- 
Generators for the n-slice filtration.
These are G-spectra of the form G ∧_H S^k where k ≥ dim_func(H, n).
Here we keep the realization abstract via `SliceCellModel`.
-/
def MainSliceGenerators (M : SliceCellModel G)
    (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) : Set (OrthogonalSpectrum G) :=
  {X | ∃ c, c ∈ MainSliceCells (G := G) O d n ∧ M.cellObj c = X}

theorem mem_mainSliceGenerators_iff
    (M : SliceCellModel G) (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) (X : OrthogonalSpectrum G) :
    X ∈ MainSliceGenerators (G := G) M O d n ↔
      ∃ c, c ∈ MainSliceCells (G := G) O d n ∧ M.cellObj c = X := by
  rfl

/-- 
The localizing subcategory generated by a set of spectra.
Closed under equivalences, coproducts, cofibers, extensions.
-/
inductive MainInLocalizing (S : Set (OrthogonalSpectrum G)) : OrthogonalSpectrum G → Prop
  | of_generator {X : OrthogonalSpectrum G} : X ∈ S → MainInLocalizing S X
  | zero : MainInLocalizing S (ZeroSpectrum G)
  | susp {X : OrthogonalSpectrum G} :
      MainInLocalizing S X → MainInLocalizing S (SuspSpectrum X)
  | cofiber {X Y : OrthogonalSpectrum G} :
      MainInLocalizing S X → MainInLocalizing S Y →
      MainInLocalizing S (CofiberSpectrum X Y)
  | colim {ι : Type u} (F : ι → OrthogonalSpectrum G) :
      (∀ i, MainInLocalizing S (F i)) → MainInLocalizing S (ColimSpectrum F)

/-- 
X is n-slice connected if it belongs to the localizing subcategory generated by SliceGenerators(n).
-/
def IsSliceConnected (M : SliceCellModel G)
    (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) (X : OrthogonalSpectrum G) : Prop :=
  MainInLocalizing (MainSliceGenerators (G := G) M O d n) X

end Equivariant
