import Equivariant.IndexingSystem

namespace Equivariant

universe u v

variable {G : Type u} [Group G]

/-- Abstract interface for the ambient stable category. -/
structure SpectrumLike (G : Type u) [Group G] where
  Obj : Type v
  zero : Obj
  susp : Obj → Obj
  cofiber : Obj → Obj → Obj
  colim : {ι : Type v} → (ι → Obj) → Obj
  sliceCellObj : Subgroup G → Subgroup G → ℤ → Obj

/-- Abstract slice-cell data. Its realization is provided by `C.sliceCellObj`. -/
structure SliceCellData (G : Type u) [Group G] where
  fromSubgroup : Subgroup G
  toSubgroup : Subgroup G
  degree : ℤ

/--
`O`-admissible slice cell at level `n`:
admissible transfer, source-threshold lower bound, and nonnegative degree.
-/
def IsOSliceCell (_C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) (c : SliceCellData G) : Prop :=
  O.transfer c.fromSubgroup c.toSubgroup ∧
    d O c.fromSubgroup n ≤ c.degree ∧
      0 ≤ c.degree

def OSliceCells (C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) : Set (SliceCellData G) :=
  {c | IsOSliceCell C O d n c}

/-- Generator objects for level-`n` slice filtration. -/
def SliceGenerators (C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) : Set C.Obj :=
  {X | ∃ c, c ∈ OSliceCells C O d n ∧ C.sliceCellObj c.fromSubgroup c.toSubgroup c.degree = X}

/--
Abstract localizing closure generated by `S`: includes zero, suspension,
cofibers, and small colimits.
-/
inductive InLocalizing (C : SpectrumLike G) (S : Set C.Obj) : C.Obj → Prop
  | of_generator {X} : X ∈ S → InLocalizing C S X
  | zero : InLocalizing C S C.zero
  | susp {X} : InLocalizing C S X → InLocalizing C S (C.susp X)
  | cofiber {X Y} : InLocalizing C S X → InLocalizing C S Y →
      InLocalizing C S (C.cofiber X Y)
  | colim {ι : Type v} (F : ι → C.Obj) :
      (∀ i, InLocalizing C S (F i)) → InLocalizing C S (C.colim F)

/-- `O`-slice connectivity via localizing closure of `O`-slice generators. -/
def OSliceConnectivity (C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) (X : C.Obj) : Prop :=
  InLocalizing C (SliceGenerators C O d n) X

/-- Level-`n` of the `O`-slice filtration. -/
def OSliceFiltration (C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) : Set C.Obj :=
  {X | OSliceConnectivity C O d n X}

def OperadSliceFiltration (C : SpectrumLike G) (Oinf : NInfinityOperad G)
    (d : DimensionFunction G) (n : ℤ) : Set C.Obj :=
  OSliceFiltration C Oinf.transferSystem d n

theorem mem_oSliceFiltration_iff (C : SpectrumLike G) (O : IncompleteTransferSystem G)
    (d : DimensionFunction G) (n : ℤ) (X : C.Obj) :
    X ∈ OSliceFiltration C O d n ↔ OSliceConnectivity C O d n X := by
  rfl

theorem mem_operadSliceFiltration_iff (C : SpectrumLike G) (Oinf : NInfinityOperad G)
    (d : DimensionFunction G) (n : ℤ) (X : C.Obj) :
    X ∈ OperadSliceFiltration C Oinf d n ↔ OSliceConnectivity C Oinf.transferSystem d n X := by
  rfl

end Equivariant
