import Equivariant.Slice.Filtration

namespace Equivariant

universe u

variable {G : Type u} [Group G]

/--
Syntactic expressions generated from admissible slice cells using the
localizing operations.
-/
inductive MainSliceExpr (M : SliceCellModel G)
    (O : IncompleteTransferSystem G) (d : DimensionFunction G) (n : ℤ) :
    Type (u + 1) where
  | generator (c : MainSliceCellData G) :
      c ∈ MainSliceCells (G := G) O d n → MainSliceExpr M O d n
  | zero : MainSliceExpr M O d n
  | susp : MainSliceExpr M O d n → MainSliceExpr M O d n
  | cofiber : MainSliceExpr M O d n → MainSliceExpr M O d n → MainSliceExpr M O d n
  | colim {ι : Type u} : (ι → MainSliceExpr M O d n) → MainSliceExpr M O d n

/-- Interpretation of syntax into the ambient orthogonal-spectrum layer. -/
def MainSliceExpr.eval (M : SliceCellModel G)
    (O : IncompleteTransferSystem G) (d : DimensionFunction G) (n : ℤ) :
    MainSliceExpr (G := G) M O d n → OrthogonalSpectrum G
  | .generator c _ => M.cellObj c
  | .zero => ZeroSpectrum G
  | .susp e => SuspSpectrum (MainSliceExpr.eval M O d n e)
  | .cofiber e₁ e₂ =>
      CofiberSpectrum (MainSliceExpr.eval M O d n e₁) (MainSliceExpr.eval M O d n e₂)
  | .colim F =>
      ColimSpectrum (fun i => MainSliceExpr.eval M O d n (F i))

/--
Every syntactic expression evaluates to an object in the localizing closure
generated by admissible slice cells.
-/
theorem MainSliceExpr.eval_isSliceConnected
    (M : SliceCellModel G) (O : IncompleteTransferSystem G) (d : DimensionFunction G)
    (n : ℤ) :
    ∀ e : MainSliceExpr (G := G) M O d n,
      IsSliceConnected (G := G) M O d n (MainSliceExpr.eval M O d n e) := by
  intro e
  induction e with
  | generator c hc =>
      unfold IsSliceConnected
      exact MainInLocalizing.of_generator ⟨c, hc, rfl⟩
  | zero =>
      unfold IsSliceConnected
      exact MainInLocalizing.zero
  | susp e ih =>
      unfold IsSliceConnected at *
      exact MainInLocalizing.susp ih
  | cofiber e₁ e₂ ih₁ ih₂ =>
      unfold IsSliceConnected at *
      exact MainInLocalizing.cofiber ih₁ ih₂
  | @colim ι F ih =>
      unfold IsSliceConnected at *
      exact MainInLocalizing.colim
        (F := fun i => MainSliceExpr.eval M O d n (F i)) ih

end Equivariant
